---
- name: Configure the authentication token
  lineinfile: dest=/etc/environment
              line='export OS_TOKEN={{admin_token}}'
              insertafter='EOF'
              regexp='export OS_TOKEN={{admin_token}}'
              state=present
- name: Configure the endpoint URL
  lineinfile: dest=/etc/environment
              line='export OS_URL=http://controller:35357/v3'
              insertafter='EOF'
              regexp='export OS_URL=http://controller:35357/v3'
              state=present
- name: Configure the Identity API version
  lineinfile: dest=/etc/environment
              line='export OS_IDENTITY_API_VERSION=3'
              insertafter='EOF'
              regexp='export OS_IDENTITY_API_VERSION=3'
              state=present

#- name: Source the bashrc file
#  shell: source /root/.bashrc
#  args:
#     executable: /bin/bash
- name: Create Openstack common folder
  file: path=/openstack state=directory mode=0755
- name: Create the service entity for the Identity service
  copy: src=./files/keystone.sh  dest=/openstack/keystone.sh force=yes
- name: Create the service entity for the Identity service
  shell: bash /openstack/keystone.sh && touch /openstack/keystone.txt
  args:
    creates: /openstack/keystone.txt
  environment:
    OS_TOKEN: '{{admin_token}}'
    OS_URL: 'http://controller:35357/v3'
    OS_IDENTITY_API_VERSION: '3'
- name: Copy Admin project script
  template: src=project.sh.j2 dest=/openstack/project.sh
- name: Create Admin project
shell: bash /openstack/keystone.sh && touch /openstack/admin-pro.txt
args:
  creates: /openstack/admin-pro.txt
environment:
  OS_TOKEN: '{{admin_token}}'
  OS_URL: 'http://controller:35357/v3'
  OS_IDENTITY_API_VERSION: '3'
- name: Install Python pip
  apt: name=python-pip  state=installed allow_unauthenticated=yes
- pip: name=shade state=absent
