---
- name: Disable Keystone start on boot
  template: src=keystone.override.j2 dest=/etc/init/keystone.override
- name: Install Keystone, Apache and Memcache
  apt: name={{item}}  state=installed allow_unauthenticated=yes
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi
    - memcached
    - python-memcache
- name: Keystone configuration
  template: src=keystone.conf.j2  dest=/etc/keystone/keystone.conf
  notify:
  - restart keystone
- meta: flush_handlers
- name: Populate the Identity service database
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone
  become: yes
  become_user: root
- name: Apache main configuration
  template: src=apache2.conf.j2 dest=/etc/apache2.conf
  notify:
  - restart apache
- name: WSGI configuration
  template: src=wsgi-keystone.conf.j2 dest=/etc/apache2/sites-availablewsgi-keystone.conf
  notify:
  - restart apache
- name: Delete SQLite database
  file: path=/var/lib/keystone/keystone.db state=absent force=yes
