---
- name: Disable Keystone start on boot
  shell: echo "manual" > /etc/init/keystone.override
- name: Install Keystone, Apache and Memcache
  apt: name={{item}}  state=installed
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi
    - memcached
    - python-memcache
- name: Keystone configuration
  template: src=keystone.conf.j2  dest=/etc/keystone/keystone.conf
- name: Populate the Identity service database
  shell: keystone-manage db_sync keystone
  become: yes
  become_user: root
- name: Apache main configuration
  template: src=apache2.conf.j2 dest=/etc/apache2.conf
- name: WSGI configuration
  template: src=wsgi-keystone.conf.j2 dest=/etc/apache2/sites-availablewsgi-keystone.conf
